name: flutter_recap
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  cached_network_image: ^3.2.0
  sqflite: ^2.0.2
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.4.0
  android_alarm_manager_plus: ^2.0.5 
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mockito: ^5.0.8
  mocktail: ^0.3.0
  ## flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
